# Generated by Django 2.1.4 on 2019-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190716_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flashinfo',
            name='date',
            field=models.DateField(),
        ),
    ]
