# Generated by Django 2.1.4 on 2019-07-18 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190718_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 18)),
        ),
        migrations.AlterField(
            model_name='flashinfo',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 18)),
        ),
    ]
