# Generated by Django 2.1.4 on 2019-08-02 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190718_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 2)),
        ),
        migrations.AlterField(
            model_name='flashinfo',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 2)),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=17, null=True),
        ),
    ]
