# Generated by Django 2.2.4 on 2019-08-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190802_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 30)),
        ),
        migrations.AlterField(
            model_name='flashinfo',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 30)),
        ),
    ]
